// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/data-structures","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/data-structures","name":"数据结构管理","icon":"BlockOutlined","parentId":"ant-design-pro-layout","id":"2"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__SchemaManagement__index" */'@/pages/SchemaManagement/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/yanfang/MOM/BDC/frontend/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
