// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import BlockOutlined from '/Users/yanfang/MOM/BDC/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BlockOutlined';
export default { BlockOutlined };
